#!/usr/local/bin/python
# -*- coding: utf-8 -*-

# TEXTS #
text_01 = 'Wrong input data. Pattern: -b "PHRASE---nBP:bAP---/path/to/location"'
text_02 = 'Did not found any files'
text_05 = 'Begin and end number of lines arguments have to be digit'
text_07 = 'Did not found any file in given timestampt: '
text_09 = 'Given value does not fit pattern: "bU:eU path. Example: "1KB-1MB /path/to/somwhere/"'
text_10 = 'You did not entered correctly size range'
text_11 = 'Wrong input data. Pattern: -c "PHRASE_1---PHRASE_2---/path/to_file/file_name'
text_12 = 'Such file as indicated below does not exist or is not a file'
text_15 = 'Did not found begin and end phrases  in file '
text_16 = 'Decoding error'
text_17 = 'Given value does not fit pattern: "bU:eU path. Example: "HH:MM:SS-DD/MM/YYYY HH:MM:SS-DD/MM/YYYY /path/to/somwhere/"'
text_18 = 'Entered data does not match to pattern'
text_19 = 'Did not found any file from given timestamp '
text_20 = 'Path '
text_21 = ' is empty'
text_22 = 'Not found any empty files in '
text_23 = ' does not exist'
text_24 = 'Please look at pattern for function below:'
text_25 = 'Where:'
text_26 = 'bU - begin size Unit'
text_27 = 'eU - end size Unit'
text_28 = 'Examples:'
text_29 = 'Explanations:'
text_30 = '- path at the end is optional'
text_31 = '- putting pure number will be parsed to bytes B'
text_32 = '- putting pure unit will be parsed to 1 such unit'
text_33 = 'You forgot about size range'
text_34 = 'There is not such unit as: '
text_35 = 'Begin size cannot be bigger than end size'
text_36 = 'Known units:'
